### ISSUE TITLE
Performance between the implementation and the original version

### ISSUE THREAD

**Issue by wen-yuan-zhang** [Ending2015a/hash-grid-encoding#2]
Thanks for your work! I know it is difficult to transfer hash encoding to pure python implementation. I am wondering the performance (i.e. PSNR, rendering quality) between this implementation and the original cuda/c++ version. Have you tested it on NeRF synthetic dataset or other data? Thanks!

**Comment by Ending2015a** [comment]
Hello @zParquet. Thank you for your interest in this project. I wrote this project originally for the educational purpose, so I didn't test it on any benchmark or dataset. Please feel free to test it on your dataset! Also any contribution is welcome!

**Comment by Ending2015a** [comment]
Hello. I'm closing this issue. Please feel free to reopen it if you have any further questions.
